### ISSUE TITLE
Dependency Conflict: huggingface-hub=0.0.2

### ISSUE THREAD

**Issue by carlini** [stanford-crfm/mistral#106]
**Describe the bug**
When running the provided install steps (on two different VMs) I reached the same error after running

`conda env create -f environments/environment-gpu.yaml`

The conda environment fails to build

```The conflict is caused by:
    The user requested huggingface-hub==0.0.2
    transformers 4.16.0.dev0 depends on huggingface-hub<1.0 and >=0.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

I believe this could be fixed by giving a specific (older) transformers version, or by updating the huggingface-hub version to 0.1.0 (if that works the code).

**To Reproduce**
On a machine with CUDA11 run

```git clone https://github.com/stanford-crfm/mistral.git
cd mistral
conda env create -f environments/environment-gpu.yaml ```

**Expected behavior**
The install works correctly without giving the error.

**Additional context**
Verified on two different VMs with different GPUs and OS versions.

**Comment by J38** [comment]
Apologies for the late reply. I've updated `main` with instructions for building the Mistral environment. I've just built this environment today and ran the Mistral tutorial and it looks like it's working great. Please let me know if there are any other issues.

This is using `transformers==4.17.0` and `datasets=2.0.0` for reference.

**Comment by J38** [comment]
For reference:

```
conda create -n mistral python=3.8.12
conda activate mistral
conda install pytorch cudatoolkit=11.3 -c pytorch
pip install transformers datasets huggingface-hub deepspeed jsonlines quinine wandb
```
