### ISSUE TITLE
update documentation on accessing new Mistral checkpoints on HF Hub

### ISSUE THREAD

**Issue by dlwh** [stanford-crfm/mistral#123]
**Describe the bug**

Currently README.md has incorrect directions for accessing checkpoints from the HF Hub. Per #86 they're on the hub as branches:

>  if you look at the different branches, you should see all 610 checkpoints (see here: https://huggingface.co/stanford-crfm/arwen-gpt2-medium-x21/tree/main).

but the readme has them as separate repos

> git clone https://huggingface.co/stanford-crfm/arwen-x21-checkpoint-400000

@J38 is this what you meant in #109 ?

**Comment by J38** [comment]
This should be fixed now on `main` .
