### ISSUE TITLE
Difference in models uploaded before and after June 20th?

### ISSUE THREAD

**Issue by msclar** [stanford-crfm/mistral#182]
Hi,

I write because I am seeing some significant differences between the models uploaded before and after June 20th to [huggingface](https://huggingface.co/stanford-crfm).  I was wondering if you could provide some clarity on what changed with the latest update!

More precisely, I ran an experiment where I successfully trained a RoBERTa-base model to classify articles generated by each of the gpt2-medium models, using the versions before the June update. When I train a RoBERTa-base model to classify articles generated by the new gpt2-medium models, accuracy drops to ~random level.

I would greatly appreciate it if you could let us know what changed between the two versions, to be able to draw conclusions correctly from our experiments.

Many thanks!

**Comment by dlwh** [comment]
Sorry for being slow! The big change is that the default checkpoint ("main") went from being step 90k to the final checkpoint (which is 400k).  We were inadvertently sorting lexicographically as opposed to numerically, so the main/default checkpoints were under-trained.

**Comment by msclar** [comment]
Thank you for the clarification! This helps us reassess our conclusions, since we were analyzing an undertrained checkpoint.

Thanks again!
