### ISSUE TITLE
Last batch dropped during preprocessing

### ISSUE THREAD

**Issue by toizzy** [stanford-crfm/mistral#189]
`batch_tokenize` does not return the last batch, which is the remainder after dividing by the preprocessing batch_size. Up to 1,000 lines can be dropped from preprocessing.

 This would be fixed by adding a yield after the for loop in the `batched()` function at `mistral/src/corpora/tokenization_utils.py#L22`

**Comment by dlwh** [comment]
fixed in fa404d7. Accidentally got dropped in a PR and I missed it in review
