### ISSUE TITLE
Distributed Training: Data seem to be identical across processes

### ISSUE THREAD

**Issue by HanGuo97** [stanford-crfm/mistral#194]
**Describe the bug**
When using multiple GPUs, the data fed into each process seem to be identical across processes. This effectively makes data parallelism redundant.

**To Reproduce**
Modify the following function below
```python
class CustomOnlineBenchmarkTrainer(OnlineBenchmarkTrainer):

    def training_step(
        self,
        model: torch.nn.Module,
        inputs: Dict[str, Union[torch.Tensor, Any]],
    ) -> torch.Tensor:
        print(inputs)
        ...
```

**Expected behavior**
Data should be different across processes.

**Additional context**
HuggingFace's `Trainer` shards the dataset [in this function](https://github.com/huggingface/transformers/blob/v4.18.0/src/transformers/trainer.py#L656). However, the modified `OnlineBenchmarkTrainer` overwrites this behavior [here](https://github.com/stanford-crfm/mistral/blob/main/src/core/trainer.py#L153).

**Comment by dlwh** [comment]
that's not good! I will get that fixed asap

**Comment by dlwh** [comment]
could you pull and give that a try?

**Comment by HanGuo97** [comment]
This works like a charm. Thanks for the (super responsive) fix!!
