### ISSUE TITLE
Bug - Current Evaluation Loads Incorrect GPT-2 Model

### ISSUE THREAD

**Issue by siddk** [stanford-crfm/mistral#83]
With current evaluation code (anything not called directly via `train.py`) we end up loading the default Hugging Face GPT-2 Model (e.g., in all our evaluation scripts). This is problematic because the model we use while training implement the FP16 stability heuristics -- including further scaling the scaled dot-product attention by `1 / layer_idx`.

This is a subtle bug in that the default Hugging Face model can still load the correct weights (we're only adding algorithmic logic, no extra parameters), but this significantly hurts evaluation performance.

Fixes for this would require changing the default model to be loaded to be the MistralGPT2 model with the layer-wise scaling enabled.

**Comment by J38** [comment]
@siddk - this is going to be fixed by our update to transformers, right?

**Comment by dlwh** [comment]
I suspect this is fixed (as suggested by @J38)?

**Comment by dlwh** [comment]
closing this because surely it's fine now
