### ISSUE TITLE
Push Stability Fixes / Create Issues on HF Transformers

### ISSUE THREAD

**Issue by siddk** [stanford-crfm/mistral#85]
We have a series of stability fixes (GPT-2 Initialization, stability things, etc.) in our codebase, that aren't present in the default GPT-2 model on HF Transformers.

We should push the fixes that don't change semantics (EDIT: it's not clear to me any of these changes keep semantics _entirely_ the same) as PRs, and open issues to figure out with the HF team directly how to incorporate these new fixes.

Might make sense to create a new GPT-2 model... but also feels like adding overhead.

**Comment by rizar** [comment]
Hi Sidd,

Mistral seems like a great initiative!

I have found the following PR: https://github.com/huggingface/transformers/pull/13573

Should I presume that this issue is addressed?

**Comment by siddk** [comment]
Hey Dima - yes, sorry! All of the necessary code is now natively in HF! Closing this issue now, but feel free to reopen/ping me directly in case you want more details about how to replicate Mistral training with `transformers`.

**Comment by rizar** [comment]
Thanks for the quick reply, Sidd! I really appreciate the effort that you put into merging this to HF.
