### ISSUE TITLE
Sharing Models through the Hugging Face Hub

### ISSUE THREAD

**Issue by osanseviero** [stanford-crfm/mistral#86]
Hi CRFM team!

Mistral is very exciting! I see you currently share your model checkpoints through links to a hosted server. Would you be interested in sharing the pretrained models in the [Hugging Face Hub](http://hf.co/models)? We already have a similar collaboration with the Stanford NLP group (see [org](https://huggingface.co/stanfordnlp)).

The Hub offers free hosting of over 20K models, and it would make your work more accessible and visible to the rest of the community. Some of the benefits of sharing your models would be:

* forget about the pain of managing the hosting
* built-in versioning
* commit history and diffs
* repos provide useful metadata about their tasks, languages, metrics, etc that is useful for discoverability but also to understand the model

Creating the repos and adding new models should be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/adding-a-model) explaining the process in case you're interested. Please let us know if you would be interested and if you have any questions.

In a future we could also integrate this to our Inference API so users can play with the models directly in the browser with our widgets.

Happy to hear your thoughts,
**Omar and the Hugging Face team**

cc @lewtun @anton-l @LysandreJik

**Comment by siddk** [comment]
Hey @osanseviero - this is something we were talking about, but one clarification; would you be able to host *all* 610 checkpoints for each of the 10 runs (6100 checkpoints total, ~22TB)? 

We figured this could get complicated (and expensive), but if you can do it, we can go through the process it! Would also let us push our slightly tweaked/stable GPT-2 model definition up to HF as well!

**Comment by osanseviero** [comment]
Hey @siddk! That's great to hear. Yes, we're up to host all your checkpoints if you would really like to share all of them. The way I would suggest to do it is to have one repository for each experiment and do a new commit for each checkpoint. Users would then be able to load the checkpoint from a given revision and the working widget would use the latest checkpoint, which should correspond to step 400,000.

**Comment by siddk** [comment]
Sounds great. I think we need to do a bit of clean-up on our side this week then, but we will start the process above early next week! Looking forward to working through this with you.

And a heads up - this probably won't be the last set of models we train 🙂 ! Looking forward to fostering a stronger relationship with HF as we keep exploring!

**Comment by dlwh** [comment]
@siddk what's the definition of done here? is it having uploaded 6100 model checkpoints? (as opposed to the 10 that are there now?) Are we going to do that?

**Comment by siddk** [comment]
These should all be done - if you look at the different branches, you should see all 610 checkpoints (see here: https://huggingface.co/stanford-crfm/arwen-gpt2-medium-x21/tree/main).

**Comment by dlwh** [comment]
ok, our readme.md says `git clone https://huggingface.co/stanford-crfm/arwen-x21-checkpoint-400000` so we should probably fix

**Comment by dlwh** [comment]
i'm closing this and i opened #123
